<?php
declare(strict_types=1);
$estados = ['registrado','anulado'];
$selectedCliente = (int) ($filters['cliente_id'] ?? 0);
$selectedCaso = (int) ($filters['caso_id'] ?? 0);
$canAnnul = in_array('*', $currentUser['permissions'] ?? [], true) || in_array('finanzas.anular', $currentUser['permissions'] ?? [], true);
?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card"><div class="card-header"><h2 class="card-title">Registrar gasto</h2></div><div class="card-body">
            <form action="/finanzas/gastos" method="post" data-ajax-form>
                <div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" data-ajax-select data-url="/api/select/clientes" data-empty-label="Seleccione" required><option value="">Seleccione</option></select></div>
                <div class="mb-2"><label class="form-label">Caso</label><select class="form-select" name="caso_id" data-ajax-select data-url="/api/select/casos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Sin caso"><option value="">Sin caso</option></select></div>
                <div class="mb-2"><label class="form-label">Soporte documental</label><select class="form-select" name="documento_id" data-ajax-select data-url="/api/select/documentos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Sin soporte"><option value="">Sin soporte</option></select></div>
                <div class="mb-2"><label class="form-label">Concepto</label><input class="form-control" name="concepto" required></div>
                <div class="row g-2"><div class="col-sm-6"><label class="form-label">Categoria</label><input class="form-control" name="categoria"></div><div class="col-sm-6"><label class="form-label">Fecha</label><input class="form-control" name="fecha_gasto" type="date" value="<?= e(date('Y-m-d')) ?>" required></div></div>
                <div class="row g-2 mt-1"><div class="col-sm-6"><label class="form-label">Monto</label><input class="form-control" name="monto" type="number" min="0.01" step="0.01" required></div><div class="col-sm-6"><label class="form-label">Moneda</label><select class="form-select" name="moneda" required><?php foreach ($catalogos['moneda'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= $item['codigo'] === 'COP' ? 'selected' : '' ?>><?= e($item['codigo']) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-3 mt-2"><label class="form-label">Observaciones</label><textarea class="form-control" name="observaciones" rows="3"></textarea></div>
                <input type="hidden" name="estado" value="registrado">
                <button class="btn btn-primary" type="submit">Registrar gasto</button>
            </form>
        </div></div>
    </div>
    <div class="col-xl-8">
        <div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get" action="/finanzas/gastos"><div class="col-md-3"><label class="form-label">Busqueda</label><input class="form-control" name="q" value="<?= e($filters['q'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= ($filters['estado'] ?? '') === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" data-ajax-select data-url="/api/select/clientes" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($clientes as $cliente): ?><?php if ($selectedCliente === (int) $cliente['id']): ?><option value="<?= (int) $cliente['id'] ?>" selected><?= e($cliente['nombre_razon_social']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Caso</label><select class="form-select" name="caso_id" data-ajax-select data-url="/api/select/casos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($casos as $caso): ?><?php if ($selectedCaso === (int) $caso['id']): ?><option value="<?= (int) $caso['id'] ?>" selected><?= e($caso['titulo']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-1 d-grid"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button></div></form></div></div>
        <div class="card"><div class="card-header"><h2 class="card-title">Gastos operativos</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Concepto</th><th>Cliente</th><th>Monto</th><th>Soportes</th><th>Registrado por</th><th>Estado</th><th></th></tr></thead><tbody>
        <?php foreach ($gastos['items'] as $gasto): ?><tr><td><strong><?= e($gasto['concepto']) ?></strong><div class="small text-secondary"><?= e($gasto['categoria'] ?? 'Sin categoria') ?> - <?= e($gasto['fecha_gasto']) ?></div></td><td><?= e($gasto['cliente_nombre']) ?><div class="small text-secondary"><?= e($gasto['caso_titulo'] ?? 'Sin caso') ?></div></td><td><?= e($gasto['moneda']) ?> <?= number_format((float) $gasto['monto'], 2) ?></td><td><?= e($gasto['soportes'] ?? 'Sin soporte') ?></td><td><?= e($gasto['registrado_por_nombre'] ?? '') ?></td><td><span class="badge text-bg-secondary" data-finance-state><?= e($gasto['estado']) ?></span></td><td><details><summary class="small">Editar</summary><form class="mt-2" action="/finanzas/gastos/<?= (int) $gasto['id'] ?>" method="post" data-ajax-form><input type="hidden" name="_method" value="PATCH"><input type="hidden" name="cliente_id" value="<?= (int) $gasto['cliente_id'] ?>"><input type="hidden" name="caso_id" value="<?= e((string) ($gasto['caso_id'] ?? '')) ?>"><input type="hidden" name="fecha_gasto" value="<?= e($gasto['fecha_gasto']) ?>"><input class="form-control form-control-sm mb-1" name="concepto" value="<?= e($gasto['concepto']) ?>"><input class="form-control form-control-sm mb-1" name="categoria" value="<?= e($gasto['categoria'] ?? '') ?>"><input class="form-control form-control-sm mb-1" name="monto" type="number" min="0.01" step="0.01" value="<?= e((string) $gasto['monto']) ?>"><select class="form-select form-select-sm mb-1" name="moneda"><?php foreach ($catalogos['moneda'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= $gasto['moneda'] === $item['codigo'] ? 'selected' : '' ?>><?= e($item['codigo']) ?></option><?php endforeach; ?></select><select class="form-select form-select-sm mb-1" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= $gasto['estado'] === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select><textarea class="form-control form-control-sm mb-2" name="observaciones" rows="2"><?= e($gasto['observaciones'] ?? '') ?></textarea><button class="btn btn-sm btn-primary">Guardar</button></form></details><?php if ($canAnnul && $gasto['estado'] !== 'anulado'): ?><button class="btn btn-sm btn-outline-danger mt-2" data-action="/finanzas/gastos/<?= (int) $gasto['id'] ?>/anular" data-prompt="Motivo de anulacion">Anular</button><?php endif; ?></td></tr><?php endforeach; ?>
        <?php if ($gastos['items'] === []): ?><tr><td colspan="7" class="text-center text-secondary py-4">No hay gastos.</td></tr><?php endif; ?>
        </tbody></table></div><div class="card-footer small text-secondary">Total: <?= (int) $gastos['total'] ?></div></div>
    </div>
</div>
