<?php declare(strict_types=1); $estados = ['nuevo','contactado','consulta','cotizacion','negociacion','ganado','perdido']; ?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-5">
        <div class="card"><div class="card-header"><h2 class="card-title"><?= e($prospecto['nombre']) ?></h2></div><div class="card-body">
            <dl class="row mb-0"><dt class="col-sm-4">Estado</dt><dd class="col-sm-8"><?= e($prospecto['estado']) ?></dd><dt class="col-sm-4">Empresa</dt><dd class="col-sm-8"><?= e($prospecto['empresa'] ?? '') ?></dd><dt class="col-sm-4">Contacto</dt><dd class="col-sm-8"><?= e($prospecto['email'] ?? '') ?><br><?= e($prospecto['telefono'] ?? '') ?></dd><dt class="col-sm-4">Responsable</dt><dd class="col-sm-8"><?= e($prospecto['responsable_nombre'] ?? 'Sin asignar') ?></dd><dt class="col-sm-4">Cliente</dt><dd class="col-sm-8"><?php if ($prospecto['converted_cliente_id'] !== null): ?><a href="/clientes/<?= (int) $prospecto['converted_cliente_id'] ?>"><?= e($prospecto['cliente_nombre'] ?? ('Cliente #' . $prospecto['converted_cliente_id'])) ?></a><?php else: ?>Pendiente<?php endif; ?></dd></dl>
        </div><div class="card-footer d-flex gap-2"><a class="btn btn-outline-secondary" href="/prospectos">Volver</a><?php if ($prospecto['converted_cliente_id'] === null): ?><button class="btn btn-success" data-action="/prospectos/<?= (int) $prospecto['id'] ?>/convertir" data-confirm="Convertir prospecto en cliente?">Convertir</button><?php endif; ?></div></div>
    </div>
    <div class="col-xl-7">
        <div class="card"><div class="card-header"><h2 class="card-title">Editar prospecto</h2></div><div class="card-body">
            <form action="/prospectos/<?= (int) $prospecto['id'] ?>" method="post" data-ajax-form>
                <input type="hidden" name="_method" value="PATCH">
                <div class="row g-2"><div class="col-md-8"><label class="form-label">Nombre</label><input class="form-control" name="nombre" value="<?= e($prospecto['nombre']) ?>" required></div><div class="col-md-4"><label class="form-label">Tipo</label><select class="form-select" name="tipo_persona"><option value="natural" <?= $prospecto['tipo_persona'] === 'natural' ? 'selected' : '' ?>>Natural</option><option value="juridica" <?= $prospecto['tipo_persona'] === 'juridica' ? 'selected' : '' ?>>Juridica</option></select></div></div>
                <div class="row g-2 mt-1"><div class="col-md-4"><label class="form-label">Tipo doc.</label><select class="form-select" name="tipo_documento"><option value="">Seleccione</option><?php foreach ($catalogos['tipo_documento'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= ($prospecto['tipo_documento'] ?? '') === $item['codigo'] ? 'selected' : '' ?>><?= e($item['codigo']) ?></option><?php endforeach; ?></select></div><div class="col-md-8"><label class="form-label">Documento</label><input class="form-control" name="numero_documento" value="<?= e($prospecto['numero_documento'] ?? '') ?>"></div></div>
                <div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">Correo</label><input class="form-control" name="email" type="email" value="<?= e($prospecto['email'] ?? '') ?>"></div><div class="col-md-6"><label class="form-label">Telefono</label><input class="form-control" name="telefono" value="<?= e($prospecto['telefono'] ?? '') ?>"></div></div>
                <div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">Empresa</label><input class="form-control" name="empresa" value="<?= e($prospecto['empresa'] ?? '') ?>"></div><div class="col-md-6"><label class="form-label">Fuente</label><select class="form-select" name="fuente"><option value="">Seleccione</option><?php foreach ($catalogos['origen_fuente'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= ($prospecto['fuente'] ?? '') === $item['codigo'] ? 'selected' : '' ?>><?= e($item['etiqueta']) ?></option><?php endforeach; ?></select></div></div>
                <div class="row g-2 mt-1"><div class="col-md-4"><label class="form-label">Estado</label><select class="form-select" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= $prospecto['estado'] === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Responsable</label><select class="form-select" name="responsable_usuario_id" data-ajax-select data-url="/api/select/usuarios" data-empty-label="Sin asignar"><option value="">Sin asignar</option><?php if (($prospecto['responsable_usuario_id'] ?? null) !== null): ?><option value="<?= (int) $prospecto['responsable_usuario_id'] ?>" selected><?= e($prospecto['responsable_nombre'] ?? ('Usuario #' . $prospecto['responsable_usuario_id'])) ?></option><?php endif; ?></select></div><div class="col-md-4"><label class="form-label">Valor</label><input class="form-control" name="valor_estimado" type="number" step="0.01" min="0" value="<?= e($prospecto['valor_estimado'] ?? '') ?>"></div></div>
                <input type="hidden" name="tratamiento_datos_autorizado" value="0"><label class="form-check my-3"><input class="form-check-input" type="checkbox" name="tratamiento_datos_autorizado" value="1" <?= (int) $prospecto['tratamiento_datos_autorizado'] === 1 ? 'checked' : '' ?>><span class="form-check-label">Autoriza tratamiento de datos</span></label>
                <div class="mb-3"><label class="form-label">Notas</label><textarea class="form-control" name="notas" rows="4"><?= e($prospecto['notas'] ?? '') ?></textarea></div>
                <button class="btn btn-primary" type="submit">Guardar</button>
            </form>
        </div></div>
    </div>
</div>
