<?php
declare(strict_types=1);
$estados = ['registrado','anulado'];
$canReveal = in_array('*', $currentUser['permissions'] ?? [], true) || in_array('finanzas.revelar', $currentUser['permissions'] ?? [], true);
$canAnnul = in_array('*', $currentUser['permissions'] ?? [], true) || in_array('finanzas.anular', $currentUser['permissions'] ?? [], true);
$selectedCliente = (int) ($filters['cliente_id'] ?? 0);
$selectedCaso = (int) ($filters['caso_id'] ?? 0);
$selectedHonorario = (int) ($filters['honorario_id'] ?? 0);
?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card"><div class="card-header"><h2 class="card-title">Registrar pago</h2></div><div class="card-body">
            <form action="/finanzas/pagos" method="post" data-ajax-form data-payment-form>
                <div class="mb-2"><label class="form-label">Honorario</label><select class="form-select" name="honorario_id" data-payment-honorario data-ajax-select data-url="/api/select/honorarios" data-extra-query="saldo=1" data-empty-label="Sin honorario"><option value="">Sin honorario</option></select></div>
                <div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" data-payment-client data-ajax-select data-url="/api/select/clientes" data-empty-label="Seleccione" required><option value="">Seleccione</option></select></div>
                <div class="mb-2"><label class="form-label">Caso</label><select class="form-select" name="caso_id" data-payment-case data-ajax-select data-url="/api/select/casos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Sin caso"><option value="">Sin caso</option></select></div>
                <div class="row g-2"><div class="col-sm-6"><label class="form-label">Monto</label><input class="form-control" name="monto" data-payment-amount type="number" min="0.01" step="0.01" required></div><div class="col-sm-6"><label class="form-label">Moneda</label><select class="form-select" name="moneda" data-payment-currency required><?php foreach ($catalogos['moneda'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= $item['codigo'] === 'COP' ? 'selected' : '' ?>><?= e($item['codigo']) ?></option><?php endforeach; ?></select></div></div>
                <div class="row g-2 mt-1"><div class="col-sm-6"><label class="form-label">Fecha</label><input class="form-control" name="fecha_pago" type="date" value="<?= e(date('Y-m-d')) ?>" required></div><div class="col-sm-6"><label class="form-label">Metodo</label><select class="form-select" name="metodo_pago" required><option value="">Seleccione</option><?php foreach ($catalogos['metodo_pago'] as $item): ?><option value="<?= e($item['codigo']) ?>"><?= e($item['etiqueta']) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-2 mt-2"><label class="form-label">Referencia protegida</label><input class="form-control" name="referencia" maxlength="180"></div>
                <div class="mb-3"><label class="form-label">Observaciones</label><textarea class="form-control" name="observaciones" rows="3"></textarea></div>
                <input type="hidden" name="estado" value="registrado">
                <button class="btn btn-primary" type="submit">Registrar pago</button>
            </form>
        </div></div>
    </div>
    <div class="col-xl-8">
        <div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get" action="/finanzas/pagos"><div class="col-md-3"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" data-ajax-select data-url="/api/select/clientes" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($clientes as $cliente): ?><?php if ($selectedCliente === (int) $cliente['id']): ?><option value="<?= (int) $cliente['id'] ?>" selected><?= e($cliente['nombre_razon_social']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= ($filters['estado'] ?? '') === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Caso</label><select class="form-select" name="caso_id" data-ajax-select data-url="/api/select/casos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($casos as $caso): ?><?php if ($selectedCaso === (int) $caso['id']): ?><option value="<?= (int) $caso['id'] ?>" selected><?= e($caso['titulo']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Honorario</label><select class="form-select" name="honorario_id" data-ajax-select data-url="/api/select/honorarios" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($honorarios as $honorario): ?><?php if ($selectedHonorario === (int) $honorario['id']): ?><option value="<?= (int) $honorario['id'] ?>" selected><?= e(catalog_label($catalogos['concepto_honorario'], $honorario['concepto'])) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-1 d-grid"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button></div></form></div></div>
        <div class="card"><div class="card-header"><h2 class="card-title">Pagos registrados</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Cliente</th><th>Monto</th><th>Metodo</th><th>Referencia</th><th>Registrado por</th><th>Estado</th><th></th></tr></thead><tbody>
        <?php foreach ($pagos['items'] as $pago): ?><tr><td><?= e($pago['cliente_nombre']) ?><div class="small text-secondary"><?= e($pago['caso_titulo'] ?? $pago['honorario_concepto'] ?? 'Sin vinculo') ?></div></td><td><?= e($pago['moneda']) ?> <?= number_format((float) $pago['monto'], 2) ?><div class="small text-secondary"><?= e($pago['fecha_pago']) ?></div></td><td><?= e(catalog_label($catalogos['metodo_pago'], $pago['metodo_pago'])) ?></td><td><span data-payment-reference="<?= (int) $pago['id'] ?>"><?= e($pago['referencia_masked']) ?></span><?php if ($canReveal && $pago['referencia_masked'] !== ''): ?> <button class="btn btn-sm btn-outline-secondary" data-payment-reveal="/finanzas/pagos/<?= (int) $pago['id'] ?>/revelar" data-target="<?= (int) $pago['id'] ?>"><i class="bi bi-eye"></i></button><?php endif; ?></td><td><?= e($pago['registrado_por_nombre'] ?? '') ?></td><td><span class="badge text-bg-secondary" data-finance-state><?= e($pago['estado']) ?></span></td><td><?php if ($canAnnul && $pago['estado'] !== 'anulado'): ?><button class="btn btn-sm btn-outline-danger" data-action="/finanzas/pagos/<?= (int) $pago['id'] ?>/anular" data-prompt="Motivo de anulacion">Anular</button><?php endif; ?></td></tr><?php endforeach; ?>
        <?php if ($pagos['items'] === []): ?><tr><td colspan="7" class="text-center text-secondary py-4">No hay pagos.</td></tr><?php endif; ?>
        </tbody></table></div><div class="card-footer small text-secondary">Total: <?= (int) $pagos['total'] ?></div></div>
    </div>
</div>
