<?php
declare(strict_types=1);
$estados = ['pendiente','parcial','pagado','cancelado'];
$selectedCliente = (int) ($filters['cliente_id'] ?? 0);
$selectedCaso = (int) ($filters['caso_id'] ?? 0);
$canAnnul = in_array('*', $currentUser['permissions'] ?? [], true) || in_array('finanzas.anular', $currentUser['permissions'] ?? [], true);
?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card"><div class="card-header"><h2 class="card-title">Nuevo honorario</h2></div><div class="card-body">
            <form action="/finanzas/honorarios" method="post" data-ajax-form>
                <div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" data-ajax-select data-url="/api/select/clientes" data-empty-label="Seleccione" required><option value="">Seleccione</option></select></div>
                <div class="mb-2"><label class="form-label">Caso</label><select class="form-select" name="caso_id" data-ajax-select data-url="/api/select/casos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Sin caso"><option value="">Sin caso</option></select></div>
                <div class="mb-2"><label class="form-label">Concepto</label><select class="form-select" name="concepto" required><option value="">Seleccione</option><?php foreach ($catalogos['concepto_honorario'] as $item): ?><option value="<?= e($item['codigo']) ?>"><?= e($item['etiqueta']) ?></option><?php endforeach; ?></select></div>
                <div class="row g-2"><div class="col-sm-6"><label class="form-label">Monto</label><input class="form-control" name="monto" type="number" min="0.01" step="0.01" required></div><div class="col-sm-6"><label class="form-label">Moneda</label><select class="form-select" name="moneda" required><?php foreach ($catalogos['moneda'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= $item['codigo'] === 'COP' ? 'selected' : '' ?>><?= e($item['codigo']) ?></option><?php endforeach; ?></select></div></div>
                <div class="row g-2 mt-1"><div class="col-sm-6"><label class="form-label">Fecha</label><input class="form-control" name="fecha_acuerdo" type="date" value="<?= e(date('Y-m-d')) ?>" required></div><div class="col-sm-6"><label class="form-label">Estado</label><select class="form-select" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>"><?= e($estado) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-3 mt-2"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion" rows="3"></textarea></div>
                <button class="btn btn-primary" type="submit">Crear honorario</button>
            </form>
        </div></div>
    </div>
    <div class="col-xl-8">
        <div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get" action="/finanzas/honorarios"><div class="col-md-3"><label class="form-label">Busqueda</label><input class="form-control" name="q" value="<?= e($filters['q'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= ($filters['estado'] ?? '') === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" data-ajax-select data-url="/api/select/clientes" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($clientes as $cliente): ?><?php if ($selectedCliente === (int) $cliente['id']): ?><option value="<?= (int) $cliente['id'] ?>" selected><?= e($cliente['nombre_razon_social']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Caso</label><select class="form-select" name="caso_id" data-ajax-select data-url="/api/select/casos" data-parent-field="cliente_id" data-parent-param="cliente_id" data-empty-label="Todos"><option value="">Todos</option><?php foreach ($casos as $caso): ?><?php if ($selectedCaso === (int) $caso['id']): ?><option value="<?= (int) $caso['id'] ?>" selected><?= e($caso['titulo']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-1 d-grid"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button></div></form></div></div>
        <div class="card"><div class="card-header"><h2 class="card-title">Honorarios pactados</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Concepto</th><th>Cliente</th><th>Monto</th><th>Pagado</th><th>Estado</th><th></th></tr></thead><tbody>
        <?php foreach ($honorarios['items'] as $honorario): ?><tr><td><strong><?= e(catalog_label($catalogos['concepto_honorario'], $honorario['concepto'])) ?></strong><div class="small text-secondary"><?= e($honorario['caso_titulo'] ?? 'Sin caso') ?></div></td><td><?= e($honorario['cliente_nombre']) ?></td><td><?= e($honorario['moneda']) ?> <?= number_format((float) $honorario['monto'], 2) ?><div class="small text-secondary"><?= e($honorario['fecha_acuerdo']) ?></div></td><td><?= e($honorario['moneda']) ?> <?= number_format((float) ($honorario['total_pagado'] ?? 0), 2) ?><div class="small text-secondary">Saldo <?= number_format((float) ($honorario['saldo_pendiente'] ?? 0), 2) ?></div></td><td><span class="badge text-bg-secondary" data-finance-state><?= e($honorario['estado']) ?></span></td><td><details><summary class="small">Editar</summary><form class="mt-2" action="/finanzas/honorarios/<?= (int) $honorario['id'] ?>" method="post" data-ajax-form><input type="hidden" name="_method" value="PATCH"><input type="hidden" name="cliente_id" value="<?= (int) $honorario['cliente_id'] ?>"><input type="hidden" name="caso_id" value="<?= e((string) ($honorario['caso_id'] ?? '')) ?>"><input type="hidden" name="fecha_acuerdo" value="<?= e($honorario['fecha_acuerdo']) ?>"><select class="form-select form-select-sm mb-1" name="concepto"><?php foreach ($catalogos['concepto_honorario'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= $honorario['concepto'] === $item['codigo'] ? 'selected' : '' ?>><?= e($item['etiqueta']) ?></option><?php endforeach; ?></select><input class="form-control form-control-sm mb-1" name="monto" type="number" min="<?= e((string) ($honorario['total_pagado'] ?? '0')) ?>" step="0.01" value="<?= e((string) $honorario['monto']) ?>"><select class="form-select form-select-sm mb-1" name="moneda"><?php foreach ($catalogos['moneda'] as $item): ?><option value="<?= e($item['codigo']) ?>" <?= $honorario['moneda'] === $item['codigo'] ? 'selected' : '' ?>><?= e($item['codigo']) ?></option><?php endforeach; ?></select><select class="form-select form-select-sm mb-1" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= $honorario['estado'] === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select><textarea class="form-control form-control-sm mb-2" name="descripcion" rows="2"><?= e($honorario['descripcion'] ?? '') ?></textarea><button class="btn btn-sm btn-primary">Guardar</button></form></details><?php if ($canAnnul && $honorario['estado'] !== 'cancelado'): ?><button class="btn btn-sm btn-outline-danger mt-2" data-action="/finanzas/honorarios/<?= (int) $honorario['id'] ?>/cancelar" data-prompt="Motivo de cancelacion">Cancelar</button><?php endif; ?></td></tr><?php endforeach; ?>
        <?php if ($honorarios['items'] === []): ?><tr><td colspan="6" class="text-center text-secondary py-4">No hay honorarios.</td></tr><?php endif; ?>
        </tbody></table></div><div class="card-footer small text-secondary">Total: <?= (int) $honorarios['total'] ?></div></div>
    </div>
</div>
