<?php declare(strict_types=1); $estados = ['pendiente','parcial','pagado','cancelado']; ?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card"><div class="card-header"><h2 class="card-title">Nuevo honorario</h2></div><div class="card-body">
            <form action="/finanzas/honorarios" method="post" data-ajax-form>
                <div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" required><option value="">Seleccione</option><?php foreach ($clientes as $cliente): ?><option value="<?= (int) $cliente['id'] ?>"><?= e($cliente['nombre_razon_social']) ?></option><?php endforeach; ?></select></div>
                <div class="mb-2"><label class="form-label">Caso</label><select class="form-select" name="caso_id"><option value="">Sin caso</option><?php foreach ($casos as $caso): ?><option value="<?= (int) $caso['id'] ?>"><?= e($caso['titulo']) ?></option><?php endforeach; ?></select></div>
                <div class="mb-2"><label class="form-label">Concepto</label><input class="form-control" name="concepto" required></div>
                <div class="row g-2"><div class="col-sm-6"><label class="form-label">Monto</label><input class="form-control" name="monto" type="number" min="0.01" step="0.01" required></div><div class="col-sm-6"><label class="form-label">Moneda</label><input class="form-control" name="moneda" value="COP" maxlength="3" required></div></div>
                <div class="row g-2 mt-1"><div class="col-sm-6"><label class="form-label">Fecha</label><input class="form-control" name="fecha_acuerdo" type="date" value="<?= e(date('Y-m-d')) ?>" required></div><div class="col-sm-6"><label class="form-label">Estado</label><select class="form-select" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>"><?= e($estado) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-3 mt-2"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion" rows="3"></textarea></div>
                <button class="btn btn-primary" type="submit">Crear honorario</button>
            </form>
        </div></div>
    </div>
    <div class="col-xl-8">
        <div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get" action="/finanzas/honorarios"><div class="col-md-4"><label class="form-label">Busqueda</label><input class="form-control" name="q" value="<?= e($filters['q'] ?? '') ?>"></div><div class="col-md-3"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= ($filters['estado'] ?? '') === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id"><option value="">Todos</option><?php foreach ($clientes as $cliente): ?><option value="<?= (int) $cliente['id'] ?>" <?= (int) ($filters['cliente_id'] ?? 0) === (int) $cliente['id'] ? 'selected' : '' ?>><?= e($cliente['nombre_razon_social']) ?></option><?php endforeach; ?></select></div><div class="col-md-1 d-grid"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button></div></form></div></div>
        <div class="card"><div class="card-header"><h2 class="card-title">Honorarios pactados</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Concepto</th><th>Cliente</th><th>Monto</th><th>Estado</th><th></th></tr></thead><tbody>
        <?php foreach ($honorarios['items'] as $honorario): ?><tr><td><strong><?= e($honorario['concepto']) ?></strong><div class="small text-secondary"><?= e($honorario['caso_titulo'] ?? 'Sin caso') ?></div></td><td><?= e($honorario['cliente_nombre']) ?></td><td><?= e($honorario['moneda']) ?> <?= number_format((float) $honorario['monto'], 2) ?><div class="small text-secondary"><?= e($honorario['fecha_acuerdo']) ?></div></td><td><span class="badge text-bg-secondary" data-finance-state><?= e($honorario['estado']) ?></span></td><td><details><summary class="small">Editar</summary><form class="mt-2" action="/finanzas/honorarios/<?= (int) $honorario['id'] ?>" method="post" data-ajax-form><input type="hidden" name="_method" value="PATCH"><input type="hidden" name="cliente_id" value="<?= (int) $honorario['cliente_id'] ?>"><input class="form-control form-control-sm mb-1" name="concepto" value="<?= e($honorario['concepto']) ?>"><input class="form-control form-control-sm mb-1" name="monto" type="number" step="0.01" value="<?= e((string) $honorario['monto']) ?>"><select class="form-select form-select-sm mb-1" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= $honorario['estado'] === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-primary">Guardar</button></form></details></td></tr><?php endforeach; ?>
        <?php if ($honorarios['items'] === []): ?><tr><td colspan="5" class="text-center text-secondary py-4">No hay honorarios.</td></tr><?php endif; ?>
        </tbody></table></div><div class="card-footer small text-secondary">Total: <?= (int) $honorarios['total'] ?></div></div>
    </div>
</div>
