<?php declare(strict_types=1); $tipos = ['contrato','demanda','prueba','poder','soporte','otro']; ?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card"><div class="card-header"><h2 class="card-title">Cargar documento</h2></div><div class="card-body">
            <form action="/documentos" method="post" enctype="multipart/form-data" data-ajax-form>
                <div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id"><option value="">Segun caso o gasto</option><?php foreach ($clientes as $cliente): ?><option value="<?= (int) $cliente['id'] ?>"><?= e($cliente['nombre_razon_social']) ?></option><?php endforeach; ?></select></div>
                <div class="mb-2"><label class="form-label">Caso</label><select class="form-select" name="caso_id"><option value="">Sin caso</option><?php foreach ($casos as $caso): ?><option value="<?= (int) $caso['id'] ?>"><?= e($caso['titulo']) ?></option><?php endforeach; ?></select></div>
                <div class="mb-2"><label class="form-label">Gasto</label><select class="form-select" name="gasto_id"><option value="">Sin gasto</option><?php foreach ($gastos as $gasto): ?><option value="<?= (int) $gasto['id'] ?>"><?= e($gasto['concepto']) ?></option><?php endforeach; ?></select></div>
                <div class="mb-2"><label class="form-label">Titulo</label><input class="form-control" name="titulo" required></div>
                <div class="row g-2"><div class="col-sm-6"><label class="form-label">Tipo</label><select class="form-select" name="tipo_documental"><option value="">Sin tipo</option><?php foreach ($tipos as $tipo): ?><option value="<?= e($tipo) ?>"><?= e($tipo) ?></option><?php endforeach; ?></select></div><div class="col-sm-6"><label class="form-label">Visible portal</label><select class="form-select" name="visible_portal"><option value="0">No</option><option value="1">Si</option></select></div></div>
                <div class="mb-2 mt-2"><label class="form-label">Archivo</label><input class="form-control" type="file" name="archivo" required></div>
                <div class="mb-3"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion" rows="3"></textarea></div>
                <button class="btn btn-primary" type="submit"><i class="bi bi-cloud-arrow-up"></i> Cargar</button>
            </form>
        </div></div>
    </div>
    <div class="col-xl-8">
        <div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get" action="/documentos"><div class="col-md-4"><label class="form-label">Busqueda</label><input class="form-control" name="q" value="<?= e($filters['q'] ?? '') ?>"></div><div class="col-md-4"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id"><option value="">Todos</option><?php foreach ($clientes as $cliente): ?><option value="<?= (int) $cliente['id'] ?>" <?= (int) ($filters['cliente_id'] ?? 0) === (int) $cliente['id'] ? 'selected' : '' ?>><?= e($cliente['nombre_razon_social']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Caso</label><select class="form-select" name="caso_id"><option value="">Todos</option><?php foreach ($casos as $caso): ?><option value="<?= (int) $caso['id'] ?>" <?= (int) ($filters['caso_id'] ?? 0) === (int) $caso['id'] ? 'selected' : '' ?>><?= e($caso['titulo']) ?></option><?php endforeach; ?></select></div><div class="col-md-1 d-grid"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button></div></form></div></div>
        <div class="card"><div class="card-header"><h2 class="card-title">Repositorio privado</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Documento</th><th>Relacion</th><th>Version</th><th>Archivo</th><th></th></tr></thead><tbody>
        <?php foreach ($documentos['items'] as $documento): ?><tr><td><strong><?= e($documento['titulo']) ?></strong><div class="small text-secondary"><?= e($documento['tipo_documental'] ?? 'Sin tipo') ?><?= (int) $documento['visible_portal'] === 1 ? ' - Portal' : '' ?></div></td><td><?= e($documento['cliente_nombre'] ?? 'Sin cliente') ?><div class="small text-secondary"><?= e($documento['caso_titulo'] ?? 'Sin caso') ?></div></td><td><span class="badge text-bg-primary">v<?= e((string) ($documento['version_numero'] ?? '0')) ?></span></td><td><?= e($documento['nombre_original'] ?? 'Sin archivo') ?><div class="small text-secondary"><?= isset($documento['size_bytes']) ? number_format(((int) $documento['size_bytes']) / 1024, 1) . ' KB' : '' ?></div></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="/documentos/<?= (int) $documento['id'] ?>">Ver</a> <a class="btn btn-sm btn-outline-secondary" href="/documentos/<?= (int) $documento['id'] ?>/descargar"><i class="bi bi-download"></i></a></td></tr><?php endforeach; ?>
        <?php if ($documentos['items'] === []): ?><tr><td colspan="5" class="text-center text-secondary py-4">No hay documentos.</td></tr><?php endif; ?>
        </tbody></table></div><div class="card-footer small text-secondary">Total: <?= (int) $documentos['total'] ?></div></div>
    </div>
</div>
