<?php declare(strict_types=1); $estados = ['vigente','proximo','critico','vencido','cumplido']; $prioridades = ['baja','media','alta','critica']; ?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-5">
        <div class="card"><div class="card-header"><h2 class="card-title"><?= e($termino['titulo']) ?></h2></div><div class="card-body">
            <dl class="row mb-0"><dt class="col-sm-4">Caso</dt><dd class="col-sm-8"><?= $termino['caso_id'] ? '<a href="/casos/' . (int) $termino['caso_id'] . '">' . e($termino['caso_titulo'] ?? '') . '</a>' : 'Sin caso' ?></dd><dt class="col-sm-4">Tarea</dt><dd class="col-sm-8"><?= $termino['tarea_id'] ? '<a href="/tareas/' . (int) $termino['tarea_id'] . '">#' . (int) $termino['tarea_id'] . '</a>' : 'Sin tarea' ?></dd><dt class="col-sm-4">Vence</dt><dd class="col-sm-8"><?= e($termino['fecha_vencimiento']) ?></dd><dt class="col-sm-4">Estado</dt><dd class="col-sm-8"><span class="badge text-bg-secondary" data-term-badge><?= e($termino['estado_visual']) ?></span></dd><dt class="col-sm-4">Responsable</dt><dd class="col-sm-8"><?= e($termino['responsable_nombre'] ?? 'Sin asignar') ?></dd><dt class="col-sm-4">Cumplido</dt><dd class="col-sm-8"><?= e($termino['cumplido_at'] ?? '') ?></dd></dl>
        </div><div class="card-footer d-flex gap-2 flex-wrap"><a class="btn btn-outline-secondary" href="/terminos">Volver</a><?php if ($termino['estado'] !== 'cumplido'): ?><button class="btn btn-outline-success" data-action="/terminos/<?= (int) $termino['id'] ?>/cumplir" data-prompt="Observacion de cumplimiento" data-prompt-field="observacion">Cumplir</button><?php endif; ?><button class="btn btn-outline-danger" data-action="/terminos/<?= (int) $termino['id'] ?>/eliminar" data-confirm="Eliminar termino?">Eliminar</button></div></div>
    </div>
    <div class="col-xl-7">
        <div class="card"><div class="card-header"><h2 class="card-title">Editar termino</h2></div><div class="card-body">
            <form action="/terminos/<?= (int) $termino['id'] ?>" method="post" data-ajax-form>
                <input type="hidden" name="_method" value="PATCH">
                <div class="row g-2"><div class="col-md-6"><label class="form-label">Caso</label><select class="form-select" name="caso_id"><option value="">Sin caso</option><?php foreach ($casos as $caso): ?><option value="<?= (int) $caso['id'] ?>" <?= (int) ($termino['caso_id'] ?? 0) === (int) $caso['id'] ? 'selected' : '' ?>><?= e($caso['titulo']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Tarea</label><select class="form-select" name="tarea_id"><option value="">Sin tarea</option><?php foreach ($tareas as $tarea): ?><option value="<?= (int) $tarea['id'] ?>" <?= (int) ($termino['tarea_id'] ?? 0) === (int) $tarea['id'] ? 'selected' : '' ?>><?= e($tarea['titulo']) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-2 mt-2"><label class="form-label">Titulo</label><input class="form-control" name="titulo" value="<?= e($termino['titulo']) ?>" required></div>
                <div class="row g-2"><div class="col-md-4"><label class="form-label">Inicio</label><input class="form-control" name="fecha_inicio" type="date" value="<?= e($termino['fecha_inicio']) ?>"></div><div class="col-md-4"><label class="form-label">Vence</label><input class="form-control" name="fecha_vencimiento" type="date" value="<?= e($termino['fecha_vencimiento']) ?>"></div><div class="col-md-4"><label class="form-label">Alerta dias</label><input class="form-control" name="alerta_dias" type="number" min="0" max="90" value="<?= (int) $termino['alerta_dias'] ?>"></div></div>
                <div class="row g-2 mt-1"><div class="col-md-4"><label class="form-label">Prioridad</label><select class="form-select" name="prioridad"><?php foreach ($prioridades as $prioridad): ?><option value="<?= e($prioridad) ?>" <?= $termino['prioridad'] === $prioridad ? 'selected' : '' ?>><?= e($prioridad) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Estado</label><select class="form-select" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= $termino['estado'] === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Responsable</label><select class="form-select" name="responsable_usuario_id"><option value="">Sin asignar</option><?php foreach ($usuarios as $usuario): ?><option value="<?= (int) $usuario['id'] ?>" <?= (int) ($termino['responsable_usuario_id'] ?? 0) === (int) $usuario['id'] ? 'selected' : '' ?>><?= e($usuario['nombre']) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-3 mt-2"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion" rows="5"><?= e($termino['descripcion'] ?? '') ?></textarea></div>
                <button class="btn btn-primary" type="submit">Guardar</button>
            </form>
        </div></div>
    </div>
</div>
