<?php declare(strict_types=1); $estados = ['activo','cerrado','archivado']; $prioridades = ['baja','media','alta','critica']; ?>
<div data-feedback hidden></div>
<div class="row g-4">
    <div class="col-xl-5">
        <div class="card"><div class="card-header"><h2 class="card-title"><?= e($caso['titulo']) ?></h2></div><div class="card-body">
            <dl class="row mb-0"><dt class="col-sm-4">Cliente</dt><dd class="col-sm-8"><a href="/clientes/<?= (int) $caso['cliente_id'] ?>"><?= e($caso['cliente_nombre']) ?></a></dd><dt class="col-sm-4">Estado</dt><dd class="col-sm-8"><?= e($caso['estado']) ?></dd><dt class="col-sm-4">Prioridad</dt><dd class="col-sm-8"><?= e($caso['prioridad']) ?></dd><dt class="col-sm-4">Radicado</dt><dd class="col-sm-8"><?= e($caso['radicado'] ?? '') ?></dd><dt class="col-sm-4">Responsable</dt><dd class="col-sm-8"><?= e($caso['responsable_nombre'] ?? 'Sin asignar') ?></dd><dt class="col-sm-4">Despacho</dt><dd class="col-sm-8"><?= e($caso['despacho'] ?? '') ?></dd></dl>
        </div><div class="card-footer d-flex gap-2 flex-wrap"><a class="btn btn-outline-secondary" href="/casos">Volver</a><?php if ($caso['estado'] !== 'cerrado'): ?><button class="btn btn-outline-warning" data-action="/casos/<?= (int) $caso['id'] ?>/cerrar" data-prompt="Motivo de cierre" data-prompt-field="motivo">Cerrar</button><?php endif; ?><?php if ($caso['estado'] !== 'archivado'): ?><button class="btn btn-outline-danger" data-action="/casos/<?= (int) $caso['id'] ?>/archivar" data-prompt="Motivo de archivo" data-prompt-field="motivo">Archivar</button><?php endif; ?></div></div>
        <div class="card mt-3"><div class="card-header"><h2 class="card-title">Ficha 360</h2></div><div class="list-group list-group-flush"><a class="list-group-item list-group-item-action" href="/casos/<?= (int) $caso['id'] ?>/partes">Partes procesales</a><a class="list-group-item list-group-item-action" href="/casos/<?= (int) $caso['id'] ?>/timeline">Linea de tiempo</a><a class="list-group-item list-group-item-action" href="/terminos?caso_id=<?= (int) $caso['id'] ?>">Terminos</a><a class="list-group-item list-group-item-action" href="/audiencias?caso_id=<?= (int) $caso['id'] ?>">Audiencias</a><a class="list-group-item list-group-item-action" href="/tareas?caso_id=<?= (int) $caso['id'] ?>">Tareas</a></div></div>
    </div>
    <div class="col-xl-7">
        <div class="card"><div class="card-header"><h2 class="card-title">Editar caso</h2></div><div class="card-body">
            <form action="/casos/<?= (int) $caso['id'] ?>" method="post" data-ajax-form>
                <input type="hidden" name="_method" value="PATCH">
                <div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id" required><?php foreach ($clientes as $cliente): ?><option value="<?= (int) $cliente['id'] ?>" <?= (int) $caso['cliente_id'] === (int) $cliente['id'] ? 'selected' : '' ?>><?= e($cliente['nombre_razon_social']) ?></option><?php endforeach; ?></select></div>
                <div class="mb-2"><label class="form-label">Titulo</label><input class="form-control" name="titulo" value="<?= e($caso['titulo']) ?>" required></div>
                <div class="row g-2"><div class="col-md-4"><label class="form-label">Estado</label><select class="form-select" name="estado"><?php foreach ($estados as $estado): ?><option value="<?= e($estado) ?>" <?= $caso['estado'] === $estado ? 'selected' : '' ?>><?= e($estado) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Prioridad</label><select class="form-select" name="prioridad"><?php foreach ($prioridades as $prioridad): ?><option value="<?= e($prioridad) ?>" <?= $caso['prioridad'] === $prioridad ? 'selected' : '' ?>><?= e($prioridad) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Radicado</label><input class="form-control" name="radicado" value="<?= e($caso['radicado'] ?? '') ?>"></div></div>
                <div class="row g-2 mt-1"><div class="col-md-4"><label class="form-label">Tipo</label><input class="form-control" name="tipo_proceso" value="<?= e($caso['tipo_proceso'] ?? '') ?>"></div><div class="col-md-4"><label class="form-label">Jurisdiccion</label><input class="form-control" name="jurisdiccion" value="<?= e($caso['jurisdiccion'] ?? '') ?>"></div><div class="col-md-4"><label class="form-label">Apertura</label><input class="form-control" name="fecha_apertura" type="date" value="<?= e($caso['fecha_apertura'] ?? '') ?>"></div></div>
                <div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">Despacho</label><input class="form-control" name="despacho" value="<?= e($caso['despacho'] ?? '') ?>"></div><div class="col-md-6"><label class="form-label">Responsable</label><select class="form-select" name="responsable_usuario_id"><option value="">Sin asignar</option><?php foreach ($usuarios as $usuario): ?><option value="<?= (int) $usuario['id'] ?>" <?= (int) ($caso['responsable_usuario_id'] ?? 0) === (int) $usuario['id'] ? 'selected' : '' ?>><?= e($usuario['nombre']) ?></option><?php endforeach; ?></select></div></div>
                <div class="mb-3 mt-2"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion" rows="5"><?= e($caso['descripcion'] ?? '') ?></textarea></div>
                <button class="btn btn-primary" type="submit">Guardar</button>
            </form>
        </div></div>
    </div>
</div>
